version: '3.8'

volumes:
  postgres_data:
  static_value:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  
  web:
    build: .
    image: mishastik78/yamdb:latest
    restart: always
    volumes: 
      - static_value:/code/static/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    ports:
      - 80:80
    depends_on:
      - web
    